### PR TITLE
[WIP] Add prometheus2 job.

### PR DESCRIPTION
**Pull request by jmcarp**
* Drop deprecated properties
* Add new storage properties

@frodenas: This doesn't include a migration path, but for now I'm just interested in trying out the new release.

### CODE REVIEW

**Comment by jmcarp** [comment]
Have time to review @frodenas ? I updated alerts to the new yaml format.

**Comment by jmcarp** [comment]
Bump 😄

**Comment by jmcarp** [comment]
Conflicts resolved.

**Comment by frodenas** [comment]
FYI, I've manually merged several commits. mostly the ones related to the `prometheus2` job (https://github.com/bosh-prometheus/prometheus-boshrelease/commit/bad10ac30783a92f31e38d72211fd3c874231a41, https://github.com/bosh-prometheus/prometheus-boshrelease/commit/3d5e16852a879c68b1bbcabc22b8561c3d1e79a8, https://github.com/bosh-prometheus/prometheus-boshrelease/commit/f80b9e82cc3ebbc42118f7a5f01c015417f0425e). I'll merge the others when I figure out the migration path for existing users.

**Pull request merged**
