### PR TITLE
Vault_exporter and Vault_alerts

### PR DESCRIPTION
**Pull request by Alexvianet**
Take a look to merge Vault_exporter and Vault_alerts was based on https://github.com/grapeshot/vault_exporter

tar.gz - https://github.com/grapeshot/vault_exporter/releases/tag/v0.1.1

Also there is some grafana dashboards:
https://github.com/grapeshot/vault_exporter/blob/master/vault-mixin/dashboards.libsonnet
but i have no idea how to rework it for default grafana style to make like in example:
dashboard

Thanks

### CODE REVIEW

**Comment by frodenas** [comment]
@Alexvianet can you please remove commit https://github.com/bosh-prometheus/prometheus-boshrelease/pull/254/commits/8c89ace788369cf65c45c4f2e69666668856bc0a from this PR? It has nothing to do with the vault exporter.

**Comment by Alexvianet** [comment]
my fail sorry, revert those commit.

**Comment by Alexvianet** [comment]
@frodenas  please take a look now

**Comment by frodenas** [comment]
Thanks @Alexvianet

**Pull request merged**
