### PR TITLE
bump to cf_exporter to v1.0.0 and migrate job to bpm

### PR DESCRIPTION
**Pull request by psycofdj**
The PR bump [cf-exporter](https://github.com/bosh-prometheus/cf_exporter) from `v0.10.1` to `v1.0.0` which include:
- use of CF v3 API only instead of v2
- performance upgrade with better querying strategy 
- internal dependency bumping and CVE fixing 

The PR also migrates from oldish start/stop run script to bpm. Exporter configuration is now generated in `/var/vcap/jobs/cf_exporter/config/bpm.yml` in a much more readable way:
```yaml
---
processes:
- name: cf_exporter
  executable: "/var/vcap/packages/cf_exporter/bin/cf_exporter"
  env:
    CF_EXPORTER_WEB_LISTEN_ADDRESS: ":9193"
    CF_EXPORTER_CF_CLIENT_ID: cf_exporter
    CF_EXPORTER_CF_CLIENT_SECRET: secret
    CF_EXPORTER_CF_DEPLOYMENT_NAME: cf
    CF_EXPORTER_METRICS_ENVIRONMENT: myenv
  args:
  - "--log.level"
  - info
  - "--log.stream"
  - stderr
  - "--cf.api_url"
  - https://api.my.domain
```

@benjaminguttmann-avtq: new blob as already been uploaded

### CODE REVIEW

**Comment by benjaminguttmann-avtq** [comment]
@psycofdj what about this PR => https://github.com/bosh-prometheus/prometheus-boshrelease/pull/445 is that still needed?

**Comment by benjaminguttmann-avtq** [comment]
@psycofdj 

what about the following changes that were included in the other PR

cf_exporter.cf.api_v3_enabled: removed. Latest cf_exporter only use v3 API endpoints
cf_exporter.events.query: removed. When events are enabled, latest cf_exporter always query events of the last 10 minutes with 5k elements per page
cf_exporter.log_format: replaced by spec cf_exporter.log_stream and cf_exporter.log_json
cf_exporter.log_level: defaults to error instead of info
Operator changes

ops-file manifests/operators/enable-cf-api-v3.yml has been removed

are they still necessary ?

**Comment by psycofdj** [comment]
yes those changes are still included (they are the consequence of the new release of cf_exporter)
I forgot to delete deprecated ops-file `manifests/operators/enable-cf-api-v3.yml` which I will correct in the next commit

**Comment by benjaminguttmann-avtq** [comment]
@psycofdj is the ops file removed :D Asking because I still cannot see that it is part of the PR to remove it

**Comment by psycofdj** [comment]
you are right, missed the git add, I forced push an empty commit...
now we're good

**Review by benjaminguttmann-avtq — APPROVED** [review]

**Comment by benjaminguttmann-avtq** [comment]
thx @psycofdj  for submitting this

**Pull request merged**
