### PR TITLE
[grafana] Add timeout to nc to prevent it from freezing for bionic st…

### LINKED ISSUE #416: bionic stemcell. grafana startup freeze
Testing
- prometheus bosh release 26.4.0
- bionic stemcell 0.19

We observe grafana start freeze (post-start)

### PR DESCRIPTION
**Pull request by benjaminguttmann-avtq**
…emcell

By adding a timeout with the `-w` option we prevent nc from never returning on bionic stemcells. 

Fixes #416.

### CODE REVIEW

**Comment by frodenas** [comment]
Thanks @benjaminguttmann-avtq!

**Comment by poblin-orange** [comment]
@frodenas Hello. would you consider cutting a release soon ?

**Comment by frodenas** [comment]
@poblin-orange [v26.5.0](https://github.com/bosh-prometheus/prometheus-boshrelease/releases/tag/v26.5.0), which includes this fix, has just been released.

**Comment by poblin-orange** [comment]
thanks @frodenas

**Pull request merged**
