### PR TITLE
Make UAA client_id for bosh_exporter configurable

### PR DESCRIPTION
**Pull request by gerhard**

### CODE REVIEW

**Comment by frodenas** [comment]
@gerhard I understand that you want to configure the uaa client id, but let's not force existing users to specify it. I'd rather prefer to have a separate op-file to override it, this will allow customizing it without affecting other users.

**Comment by gerhard** [comment]
In which case, I have added the following to `prometheus-deployment-customizations.yml`, a file that I use for personal configs:

```
- type: replace
  path: /releases/name=routing/url
  path: /instance_groups/name=prometheus2/jobs/name=bosh_exporter/properties/bosh_exporter/bosh/uaa/client_id
  value: ((uaa_bosh_exporter_client_id))
```

Happy for this PR to be closed, thanks!

**Comment by frodenas** [comment]
@gerhard Willing to contribute with a PR for that op-file? :)

**Comment by gerhard** [comment]
Sure thing :)

**Comment by gerhard** [comment]
Is this what you had in mind?

**Comment by frodenas** [comment]
Merged at https://github.com/bosh-prometheus/prometheus-boshrelease/commit/fbd242a8310ff372eb76638b49484f412ca12ee9. Thanks @gerhard

**Pull request closed without merging**
