### PR TITLE
Adjust default stemcell to use xenial instead of trusty

### PR DESCRIPTION
**Pull request by gdenn**
Set ubuntu-xenial as default stemcell os type.

### CODE REVIEW

**Comment by xyloman** [comment]
I think this would be a great addition?  Has anyone run into any issues with leveraging this via an ops file to  test that all of the components work on xenial I would assume they do.

**Comment by benjaminguttmann-avtq** [comment]
Actually we applied such an ops file to our installations, and they are working fine.

**Comment by gdenn** [comment]
@benjaminguttmann-avtq perhaps we wait until we deployed prometheus with xenial on Azure and AWS and give feedback here.

We already have it running on vSphere without problems.
But i don't see any reason why it shouldn't work for the other major IaaS.

@xyloman LTS support for trusty is until 17th of April 2019.

**Comment by frodenas** [comment]
Thanks @gdenn! I've been using `xenial` stemcells for some time without any issue.

**Pull request merged**
